config/routes.rb
Psissues::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :accounts

  resources :project_accesses

  resources :responses

  resources :issues

  resources :milestones

  resources :projects do
    resources :issues do
      resources :responses
    end
    resources :milestones
    resources :categories
  end

  resources :users

  resources :categories

  resources :companies

  resources :statuses

  resources :priorities

  root :to => "projects#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :company
  belongs_to :admin, :class_name => 'User', :foreign_key => 'admin_user_id'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :issues
  has_many :responses
  belongs_to :project
  belongs_to :user, :foreign_key => 'default_assignee_id'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :accounts
  has_many :projects
  has_many :own_projects, :class_name => 'Project', :foreign_key => :owner_company_id
  has_many :users



end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :category
  belongs_to :priority
  belongs_to :status
  belongs_to :milestone

  belongs_to :opener, :class_name => 'User', :foreign_key => 'opener_user_id'
  belongs_to :assignee, :class_name => 'User', :foreign_key => 'assignee_user_id'
  has_many :responses

  scope :open, where(:status_id => 1 )
  scope :resolved, where(:status_id => 2 )
  scope :closed, where(:status_id => 3 )
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :project
  has_many :issues

end

app/models/priority.rb
class Priority < ActiveRecord::Base
  has_many :issues
  has_many :responses

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :issues
  has_many :milestones
  belongs_to :company
  belongs_to :owner, :class_name => 'Company', :foreign_key => 'owner_company_id'

  has_many :project_accesses
  has_many :users, :through => :project_accesses
end

app/models/project_access.rb
class ProjectAccess < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :issue
  belongs_to :category
  belongs_to :priority
  belongs_to :status
  belongs_to :opener, :class_name => 'User', :foreign_key => 'opener_user_id'
  belongs_to :assignee, :class_name => 'User', :foreign_key => 'assignee_user_id'
  belongs_to :responder, :class_name => 'User', :foreign_key => 'responder_user_id'
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :issues
  has_many :responses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  belongs_to :company
  has_many :administered_accounts, :class_name => 'Account', :foreign_key => 'admin_user_id'
  has_many :project_accesses
  has_many :opened_issues, :class_name => 'Issue', :foreign_key => 'opener_user_id'
  has_many :assigned_issues, :class_name => 'Issue', :foreign_key => 'assignee_user_id'
  has_many :responses, :foreign_key => 'responder_user_id'
  has_many :default_assignments, :class_name => 'Category', :foreign_key => 'default_assignee_id'

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.xml
  before_filter :set_context

  def index
    if @project
      @issues = @project.issues
    else
			@issues = Issue.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.xml
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.xml
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.xml
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to(@issue, :notice => 'Issue was successfully created.') }
        format.xml  { render :xml => @issue, :status => :created, :location => @issue }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @issue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.xml
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to(@issue, :notice => 'Issue was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @issue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.xml
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to(issues_url) }
      format.xml  { head :ok }
    end
  end

  private

  def set_context
    @project = Project.find(params[:project_id]) if params[:project_id]
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/issues/_form.html.erb
  <div class="group">
    <%= f.label :project_id, t("activerecord.attributes.issue.project_id", :default => "Project"), :class => :label %>
    <%= f.text_field :project_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :number, t("activerecord.attributes.issue.number", :default => "Number"), :class => :label %>
    <%= f.text_field :number, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :subject, t("activerecord.attributes.issue.subject", :default => "Subject"), :class => :label %>
    <%= f.text_field :subject, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :milestone_id, t("activerecord.attributes.issue.milestone_id", :default => "Milestone"), :class => :label %>
    <%= f.text_field :milestone_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :opener_user_id, t("activerecord.attributes.issue.opener_user_id", :default => "Opener user"), :class => :label %>
    <%= f.text_field :opener_user_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :assignee_user_id, t("activerecord.attributes.issue.assignee_user_id", :default => "Assignee user"), :class => :label %>
    <%= f.text_field :assignee_user_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :category_id, t("activerecord.attributes.issue.category_id", :default => "Category"), :class => :label %>
    <%= f.text_field :category_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :priority_id, t("activerecord.attributes.issue.priority_id", :default => "Priority"), :class => :label %>
    <%= f.text_field :priority_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :status_id, t("activerecord.attributes.issue.status_id", :default => "Status"), :class => :label %>
    <%= f.text_field :status_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), issues_path, :class => "text_button_padding link_button" %>
</div>

app/views/issues/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/issues/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", issues_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_issue_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_issue_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Issue</h2>
    <div class="inner">
      <%= form_for @issue, :url => issue_path(@issue), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/issues/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", issues_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_issue_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Issues</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.issue.project_id", :default => t("activerecord.labels.project_id", :default => "Project_id")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @issues.each do |issue| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= issue.id %>
          </td>
                    <td>
            <%= link_to issue.project_id, issue_path(issue) %>
          </td>
                    <td>
            <%= issue.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", issue_path(issue) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_issue_path(issue) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", issue_path(issue), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/issues/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", issues_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_issue_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Issue</h2>
    <div class="inner">
      <%= form_for :issue, :url => issues_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/issues/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", issues_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_issue_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", issue_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.issue.project_id", :default => t("activerecord.labels.project_id", :default => "Project")) %>:</b>
          <%= @issue.project_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.issue.number", :default => t("activerecord.labels.number", :default => "Number")) %>:</b>
          <%= @issue.number %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.issue.subject", :default => t("activerecord.labels.subject", :default => "Subject")) %>:</b>
          <%= @issue.subject %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.issue.milestone_id", :default => t("activerecord.labels.milestone_id", :default => "Milestone")) %>:</b>
          <%= @issue.milestone_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.issue.opener_user_id", :default => t("activerecord.labels.opener_user_id", :default => "Opener user")) %>:</b>
          <%= @issue.opener_user_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.issue.assignee_user_id", :default => t("activerecord.labels.assignee_user_id", :default => "Assignee user")) %>:</b>
          <%= @issue.assignee_user_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.issue.category_id", :default => t("activerecord.labels.category_id", :default => "Category")) %>:</b>
          <%= @issue.category_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.issue.priority_id", :default => t("activerecord.labels.priority_id", :default => "Priority")) %>:</b>
          <%= @issue.priority_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.issue.status_id", :default => t("activerecord.labels.status_id", :default => "Status")) %>:</b>
          <%= @issue.status_id %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_issue_path(@issue), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), issue_path(@issue), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>